"""Create finance analyses table

Revision ID: 5220c4866ab4
Revises: 9ce1f0c033b3
Create Date: 2026-07-29 16:21:16.441272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5220c4866ab4'
down_revision: Union[str, Sequence[str], None] = '9ce1f0c033b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=20), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_analyses_company_code'), 'finance_analyses', ['company_code'], unique=False)
    op.create_index(op.f('ix_finance_analyses_document_number'), 'finance_analyses', ['document_number'], unique=False)
    op.create_index(op.f('ix_finance_analyses_id'), 'finance_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_analyses_id'), table_name='finance_analyses')
    op.drop_index(op.f('ix_finance_analyses_document_number'), table_name='finance_analyses')
    op.drop_index(op.f('ix_finance_analyses_company_code'), table_name='finance_analyses')
    op.drop_table('finance_analyses')
    # ### end Alembic commands ###
